#!/bin/bash

source ~/mac-setup/lib

export PATH=$HOME/.homebrew/bin:$PATH

install() {
  if not_install brew; then
    mkdir ~/.homebrew && curl -L https://github.com/Homebrew/brew/tarball/master | tar xz --strip 1 -C ~/.homebrew
  fi
  verify brew
}

uninstall() {
  log_uninstalling brew
  echo y | ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall)"
}

$@
