os: osx
language: objective-c
install:
  - curl https://raw.githubusercontent.com/blcsntb/mac-setup/master/mac-setup | bash -s install && source ~/.zshrc
  - mac-setup-reinstall
script:
  - mac-setup-install
