#!/bin/bash

error_log() {
  echo ❌ $1
}

not_install() {
  if type $1 >/dev/null 2>&1; then
    false
  else
    log_installing $1
    true
  fi
}

log_installing() {
  echo 🚀 installing $1...
}

log_installed() {
  echo ✅ $1
}

verify() {
  log_installed `command -v $1`
}

log_uninstalling() {
  echo uninstalling $1...
}

validate_environment_variable() {
  name=$1
  val=$(printenv | grep $name= | sed -e s/$name=//g)
  if [[ -z "$val" ]]; then
    error_log "Miss environment variable $name. Please export it."
    exit 2
  fi
}
