#!/bin/bash

source ~/mac-setup/lib

cd ~/Library/Fonts

font_name="Meslo LG M Regular for Powerline.ttf"

install() {
  if [ ! -f "$font_name" ]; then
    log_installing "font $font_name"
    curl https://raw.githubusercontent.com/powerline/fonts/master/Meslo%20Slashed/Meslo%20LG%20M%20Regular%20for%20Powerline.ttf \
      --output "$font_name" \
      --silent
  fi
}

uninstall() {
  if [ -f "$font_name" ]; then
    log_uninstalling "font $font_name"
    rm "$font_name"
  fi
}

$@
