#!/bin/bash

source ~/mac-setup/lib

eval "$(rbenv init -)"

install() {
  if not_install rbenv; then
    brew install rbenv
    rbenv init
  fi

  if [ $(which ruby) == '/usr/bin/ruby' ]; then
    log_installing ruby
    rbenv install 2.3.0
    rbenv local 2.3.0
  fi
  verify ruby
  verify gem

  if not_install pod; then
    gem install cocoapods --quiet
  fi
  verify pod

  if not_install fastlane; then
    gem install fastlane -NV --quiet
  fi
  verify fastlane
}

$@
