#!/bin/bash

source ~/mac-setup/lib

[[ -e .jenkins.env ]] && source .jenkins.env

validate_environment_variable JENKINS_USER
validate_environment_variable JENKINS_PORT

command=$2
job=$1
shift 2

ssh -l $JENKINS_USER -p $JENKINS_PORT localhost $command $job $@
