#!/bin/bash
echo '# rvm'
--install() {
  if [ ! "$CI" ] && [ ! -d ~/.rvm ]; then
    echo '## install'
    \curl -sSL https://get.rvm.io | bash -s stable --ruby
  fi
  rvm --version
  gem install cocoapods
  gem install fastlane -NV
}
--clean() {
  if [ ! "$CI" ]; then
    echo '## clean'
    [ -d ~/.rvm ] && sudo rm -rf ~/.rvm
  fi
}
$@
