#!/bin/bash
echo '# zsh'
--config() {
  echo '## config'
  rm ~/.zshrc
  ln -s ~/mac-setup/zsh/.zshrc ~/.zshrc
  ls -l ~/.zshrc
}
--install() {
  if [ ! "$CI" ]; then
    echo '## install'
    sh -c "$(curl -fsSL https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
    --config
  fi
}
--clean() {
  echo '## clean'
  rm -rf ~/.oh-my-zsh
  rm ~/.zshrc*
}
--uninstall() {
  if [ ! "$CI" ]; then
    echo '## uninstall'
    echo y | sh -c "$(curl -fsSL https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/uninstall.sh)"
    --clean
  fi
}
$@
