export ZSH=~/.oh-my-zsh

ZSH_THEME="robbyrussell"

source $ZSH/oh-my-zsh.sh
source ~/mac-setup/rvm/rvmrc
source ~/mac-setup/nvm/nvmrc
source ~/mac-setup/python/pythonrc
source ~/mac-setup/powerline/powerlinerc
source ~/mac-setup/z/zrc
source ~/mac-setup/vscode/vscoderc
source ~/mac-setup/java/javarc
source ~/mac-setup/android/androidrc
source ~/mac-setup/fastlane/fastlanerc
source ~/mac-setup/alias/.rc
